name: CI - Update Gists from Repository
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add timestamp
        run: |
          now=$(date +"%Y%m%d%H")
          sed -i "1i # Last modified: ${now}" macros/cancel_print.cfg
          
      - name: Commit changes
        run: |
          git config --global user.name "alienboyxp"
          git config --global user.email "jrodriguez@qitec.net"
          git commit -am "Added timestamp to macro files"
          git push
          
      - uses: actions/checkout@v3
      - name: Creating start_print.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: fe225e1667da13557c270b7e5b73db10
          file_path: macros/start_print.cfg
          file_type: binary
          
      - name: Creating end_print.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 1fe5c57b40c09a9d0095d027ffc0f5d7
          file_path: macros/end_print.cfg
          file_type: binary

      - name: Creating test_kinematics.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 2bb27e5547ecca823c17435cbaf49849
          file_path: macros/test_kinematics.cfg
          file_type: binary
          
      - name: Creating test_speed.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 194649a9314f8adfceb51ae8b2e80b7b
          file_path: macros/test_speed.cfg
          file_type: binary

      - name: Creating var_globals.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: d218917893ba4ba539ce6a0b96499b4b
          file_path: macros/var_globals.cfg
          file_type: binary

      - name: Creating change_filament.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 2f9b36e9628b67ca8b527c39b8ad1992
          file_path: macros/change_filament.cfg
          file_type: binary
          
      - name: Creating move_park.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 8d93aec3888d361fdcdc77a8ce0faad7
          file_path: macros/move_park.cfg
          file_type: binary
          
      - name: Creating pause.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: c730e8f064f8515efcb87cf9d34ae774
          file_path: macros/pause.cfg
          file_type: binary
          
      - name: Creating resume.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 54da6658a58624ecff466afaebfc7004
          file_path: macros/resume.cfg
          file_type: binary 

      - name: Creating cancel_print.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 7755e06ccbbbf7029983745ceb43651a
          file_path: macros/cancel_print.cfg
          file_type: binary 
